
/* File generated by gen_cfile.py. Should not be modified. */

#include "LCNCmaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 LCNCmaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 LCNCmaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 LCNCmaster_iam_a_slave = 0;

TIMER_HANDLE LCNCmaster_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 LCNCmaster_obj1000 = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1000[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 LCNCmaster_obj1001 = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 LCNCmaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1003[] =
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t LCNCmaster_Index1003_callbacks[] =
                     {
                       NULL,
                       NULL,
                     };
                    subindex LCNCmaster_Index1003[] =
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 LCNCmaster_obj1005 = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1005_callbacks[] =
                     {
                       NULL,
                     };
                    subindex LCNCmaster_Index1005[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 LCNCmaster_obj1006 = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1006_callbacks[] =
                     {
                       NULL,
                     };
                    subindex LCNCmaster_Index1006[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1006 }
                     };

/* index 0x100C :   Guard Time */
                    UNS16 LCNCmaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */
                    UNS8 LCNCmaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 LCNCmaster_obj1014 = 0x80;	/* 128 */
                    subindex LCNCmaster_Index1014[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 LCNCmaster_highestSubIndex_obj1016 = 0;
                    UNS32 LCNCmaster_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 LCNCmaster_obj1017 = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1017_callbacks[] =
                     {
                       NULL,
                     };
                    subindex LCNCmaster_Index1017[] =
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 LCNCmaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 LCNCmaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 LCNCmaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 LCNCmaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1018[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 LCNCmaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex LCNCmaster_Index1200[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 LCNCmaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1280[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 LCNCmaster_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1400[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 LCNCmaster_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1401[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 LCNCmaster_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1402[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 LCNCmaster_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex LCNCmaster_Index1403[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1600 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1600[] =
                    {
                    };
                    subindex LCNCmaster_Index1600[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1600 }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1601 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1601[] =
                    {
                    };
                    subindex LCNCmaster_Index1601[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1601 }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1602 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1602[] =
                    {
                    };
                    subindex LCNCmaster_Index1602[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1602 }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1603 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1603[] =
                    {
                    };
                    subindex LCNCmaster_Index1603[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1603 }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 LCNCmaster_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1800_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LCNCmaster_Index1800[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 LCNCmaster_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1801_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LCNCmaster_Index1801[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 LCNCmaster_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1802_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LCNCmaster_Index1802[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 LCNCmaster_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 LCNCmaster_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LCNCmaster_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 LCNCmaster_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t LCNCmaster_Index1803_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LCNCmaster_Index1803[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&LCNCmaster_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LCNCmaster_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1A00 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1A00[] =
                    {
                    };
                    subindex LCNCmaster_Index1A00[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1A00 }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1A01 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1A01[] =
                    {
                    };
                    subindex LCNCmaster_Index1A01[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1A01 }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1A02 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1A02[] =
                    {
                    };
                    subindex LCNCmaster_Index1A02[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1A02 }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 LCNCmaster_highestSubIndex_obj1A03 = 0; /* number of subindex - 1*/
                    UNS32 LCNCmaster_obj1A03[] =
                    {
                    };
                    subindex LCNCmaster_Index1A03[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LCNCmaster_highestSubIndex_obj1A03 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable LCNCmaster_objdict[] =
{
  { (subindex*)LCNCmaster_Index1000,sizeof(LCNCmaster_Index1000)/sizeof(LCNCmaster_Index1000[0]), 0x1000},
  { (subindex*)LCNCmaster_Index1001,sizeof(LCNCmaster_Index1001)/sizeof(LCNCmaster_Index1001[0]), 0x1001},
  { (subindex*)LCNCmaster_Index1005,sizeof(LCNCmaster_Index1005)/sizeof(LCNCmaster_Index1005[0]), 0x1005},
  { (subindex*)LCNCmaster_Index1006,sizeof(LCNCmaster_Index1006)/sizeof(LCNCmaster_Index1006[0]), 0x1006},
  { (subindex*)LCNCmaster_Index1014,sizeof(LCNCmaster_Index1014)/sizeof(LCNCmaster_Index1014[0]), 0x1014},
  { (subindex*)LCNCmaster_Index1017,sizeof(LCNCmaster_Index1017)/sizeof(LCNCmaster_Index1017[0]), 0x1017},
  { (subindex*)LCNCmaster_Index1018,sizeof(LCNCmaster_Index1018)/sizeof(LCNCmaster_Index1018[0]), 0x1018},
  { (subindex*)LCNCmaster_Index1200,sizeof(LCNCmaster_Index1200)/sizeof(LCNCmaster_Index1200[0]), 0x1200},
  { (subindex*)LCNCmaster_Index1280,sizeof(LCNCmaster_Index1280)/sizeof(LCNCmaster_Index1280[0]), 0x1280},
  { (subindex*)LCNCmaster_Index1400,sizeof(LCNCmaster_Index1400)/sizeof(LCNCmaster_Index1400[0]), 0x1400},
  { (subindex*)LCNCmaster_Index1401,sizeof(LCNCmaster_Index1401)/sizeof(LCNCmaster_Index1401[0]), 0x1401},
  { (subindex*)LCNCmaster_Index1402,sizeof(LCNCmaster_Index1402)/sizeof(LCNCmaster_Index1402[0]), 0x1402},
  { (subindex*)LCNCmaster_Index1403,sizeof(LCNCmaster_Index1403)/sizeof(LCNCmaster_Index1403[0]), 0x1403},
  { (subindex*)LCNCmaster_Index1600,sizeof(LCNCmaster_Index1600)/sizeof(LCNCmaster_Index1600[0]), 0x1600},
  { (subindex*)LCNCmaster_Index1601,sizeof(LCNCmaster_Index1601)/sizeof(LCNCmaster_Index1601[0]), 0x1601},
  { (subindex*)LCNCmaster_Index1602,sizeof(LCNCmaster_Index1602)/sizeof(LCNCmaster_Index1602[0]), 0x1602},
  { (subindex*)LCNCmaster_Index1603,sizeof(LCNCmaster_Index1603)/sizeof(LCNCmaster_Index1603[0]), 0x1603},
  { (subindex*)LCNCmaster_Index1800,sizeof(LCNCmaster_Index1800)/sizeof(LCNCmaster_Index1800[0]), 0x1800},
  { (subindex*)LCNCmaster_Index1801,sizeof(LCNCmaster_Index1801)/sizeof(LCNCmaster_Index1801[0]), 0x1801},
  { (subindex*)LCNCmaster_Index1802,sizeof(LCNCmaster_Index1802)/sizeof(LCNCmaster_Index1802[0]), 0x1802},
  { (subindex*)LCNCmaster_Index1803,sizeof(LCNCmaster_Index1803)/sizeof(LCNCmaster_Index1803[0]), 0x1803},
  { (subindex*)LCNCmaster_Index1A00,sizeof(LCNCmaster_Index1A00)/sizeof(LCNCmaster_Index1A00[0]), 0x1A00},
  { (subindex*)LCNCmaster_Index1A01,sizeof(LCNCmaster_Index1A01)/sizeof(LCNCmaster_Index1A01[0]), 0x1A01},
  { (subindex*)LCNCmaster_Index1A02,sizeof(LCNCmaster_Index1A02)/sizeof(LCNCmaster_Index1A02[0]), 0x1A02},
  { (subindex*)LCNCmaster_Index1A03,sizeof(LCNCmaster_Index1A03)/sizeof(LCNCmaster_Index1A03[0]), 0x1A03},
};

const indextable * LCNCmaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = LCNCmaster_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = LCNCmaster_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1017: i = 5;*callbacks = LCNCmaster_Index1017_callbacks; break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1280: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1401: i = 10;break;
		case 0x1402: i = 11;break;
		case 0x1403: i = 12;break;
		case 0x1600: i = 13;break;
		case 0x1601: i = 14;break;
		case 0x1602: i = 15;break;
		case 0x1603: i = 16;break;
		case 0x1800: i = 17;*callbacks = LCNCmaster_Index1800_callbacks; break;
		case 0x1801: i = 18;*callbacks = LCNCmaster_Index1801_callbacks; break;
		case 0x1802: i = 19;*callbacks = LCNCmaster_Index1802_callbacks; break;
		case 0x1803: i = 20;*callbacks = LCNCmaster_Index1803_callbacks; break;
		case 0x1A00: i = 21;break;
		case 0x1A01: i = 22;break;
		case 0x1A02: i = 23;break;
		case 0x1A03: i = 24;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &LCNCmaster_objdict[i];
}

/*
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status LCNCmaster_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index LCNCmaster_firstIndex = {
  7, /* SDO_SVR */
  8, /* SDO_CLT */
  9, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  17, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const quick_index LCNCmaster_lastIndex = {
  7, /* SDO_SVR */
  8, /* SDO_CLT */
  12, /* PDO_RCV */
  16, /* PDO_RCV_MAP */
  20, /* PDO_TRS */
  24 /* PDO_TRS_MAP */
};

const UNS16 LCNCmaster_ObjdictSize = sizeof(LCNCmaster_objdict)/sizeof(LCNCmaster_objdict[0]);

CO_Data LCNCmaster_Data = CANOPEN_NODE_DATA_INITIALIZER(LCNCmaster);
